name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install flake8 mypy types-ujson types-PyYAML

      - name: Show versions
        run: |
          python --version
          pip --version
          flake8 --version || true
          mypy --version || true

      - name: Lint (flake8, 120-column)
        run: |
          flake8 . --max-line-length=120 --extend-ignore=E203,W503

      - name: Type check (mypy)
        run: |
          mypy . --install-types --non-interactive
