name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  lint-type:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install deps
      run: |
        python -m pip install -U pip
        python -m pip install flake8 mypy types-ujson
    - name: Lint
      run: flake8 .
    - name: Type check
      run: mypy . --ignore-missing-imports --install-types --non-interactive
