name: pre-commit
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system deps (if any hooks need them)
        run: |
          python -m pip install -U pip
          # Install whatever hooks will need at runtime:
          python -m pip install pre-commit flake8 mypy types-ujson types-PyYAML codespell
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
