name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build zip
        run: zip -r CueBeam-${{ github.ref_name }}.zip . -x ".git/*"
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: CueBeam-${{ github.ref_name }}.zip
          generate_release_notes: true
